@host = http://localhost:5130

// ListAsync
GET {{host}}/students/
Accept: application/json

###

// GetAsync
GET {{host}}/students/2bf954eb-b3e7-4e53-b535-4ecedee53d7e
Accept: application/json

###

// CreateAsync
POST {{host}}/students/
Accept: application/json

{
  "forename": "John",
  "surname": "Doe",
  "dateOfBirth": "1990-01"
}

###

// DeleteAsync
DELETE {{host}}/students/2bf954eb-b3e7-4e53-b535-4ecedee53d7e
Accept: application/json

